Integrate the trie
cspr-rad/kairos pull request #57
Opened 2024-04-02 06:50 UTC by Avi-D-coder

This PR just sets up the trie thread and state.
We still need all the prior logic against the btree to pre-validate transactions.
That btree will be replaced by a cache db `(PublicKey -> Account)`.

We could remove pre-validated transaction requirement with an immutable `trie::SnapshotBuilder` that supported could rollback.
However, we would still need to prevent DoS with the cache db. Real hardware is very different from the zkVM, binary tries don't perform all that well on SSDs. 

In the future we will also need to warm up the `NodeHash -> TrieNode` DB right before a txn hits the trie state thread. By cashing `TrieNode`s into ram we can move slow IO off that thread.

Next Steps after this PR:
- Adding persistence with rocks
- Adding a validating thread for testing against (like a mock contract for testing)
- General testing txns (we can replicate what I did in the trie repo).

2024-04-02 22:39 UTC, Avi-D-coder commented
I'm going to merge the txn logic between the trie and btree-cache-db before this should be merged.

2024-04-05 16:48 UTC, marijanp reviewed
Minor things, mostly requests for additional documentation

2024-04-05 16:48 UTC, marijanp commented on kairos-tx/schema.asn
> +  Epoch ::= INTEGER (0..18446744073709551615)
Shouldn't the epoch be added to SigningPayload?

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state.rs
> +
Add docstring here

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state.rs
> +    pub fn new(
Could you document what new does

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state/trie.rs
> +    fn get(&self, op_idx: usize) -> Option<&Arc<Transaction>> {
what is `op_id`?

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state/trie.rs
> +    ord: Vec<Arc<Transaction>>,
Can you document what ord is or better: give it a verboser name. Ordered here seems to refer to the ordered-transactions, that were not already in the set

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/routes/withdraw.rs
> +            anyhow!("Deposit epoch does not match current batch epoch."),
```suggestion
            anyhow!("Withdrawal epoch does not match current batch epoch."),
```

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state/trie.rs
> +pub struct BatchOutput {
Add docstring here

2024-04-05 16:48 UTC, marijanp commented on kairos-server/src/state/trie.rs
> +pub struct TrieState {
Add docstring here

2024-04-26 11:51 UTC, koxu1996 requested changes
Very solid PR :clap:. ~~One requested change is to remove epoch locking - as we discussed during last deep dive - so we avoid accepted transactions that are unexpectedly failing because of batch end/limit.~~ :speech_balloon: (This was already done, I missed it somehow.)

Also thanks for the improvement to `kairos-tx`, I will extract them to separate PR to avoid clutter in yours.

2024-04-26 14:32 UTC, Avi-D-coder commented
> One requested change is to remove epoch locking - as we discussed during last deep dive - so we avoid accepted transactions that are unexpectedly failing because of batch end/limit.

I think I already did this in https://github.com/cspr-rad/kairos/pull/57/commits/74d04449271bfc89144bfcc5d947232391b93476.

I removed the my outdated comment about batch epoch.
Although I think we might still need an epoch for time expiring transactions.

2024-04-26 14:39 UTC, koxu1996 commented
What about TTL? It could be maximum timestamp, or maximum epoch.

2024-04-26 18:34 UTC, marijanp reviewed
Where I asked for more docs for types and functions, I was more in the hope of getting explanations of how the different datastructures are supposed to be used together, what caveats there are.

2024-04-26 18:57 UTC, Avi-D-coder commented on nixos/tests/end-to-end.nix
> +    deposit_request = { "public_key": "cafebabe", "payload": deposit_payload, "signature": "cafebabe" }
Before it was `deadbeef` -> `deadbeef` -> `deadbeef`.
Now I am transferring between two accounts. 
The signatures I have just made match the public keys.

2024-04-26 18:59 UTC, Avi-D-coder commented on kairos-tx/src/asn.rs
> +    }
I'd like to move nonce to transfer and withdraw in the future.

2024-04-26 19:00 UTC, Avi-D-coder commented on kairos-tx/src/asn.rs
> +    }
However some of this duplication is to make type inference nicer.

`SigningPayload::new` vs `SigningPayload::new_*`

2024-04-26 19:15 UTC, Avi-D-coder commented on kairos-server/src/state/transactions/batch_state.rs
> +        if amount == 0 {
Made the change then noticed it causes.
`#[deny(clippy::absurd_extreme_comparisons)]`

I can make it this if you feel strongly?

```
        #[allow(clippy::absurd_extreme_comparisons)]
        if amount <= 0 {
```

2024-04-26 19:28 UTC, Avi-D-coder commented
> Where I asked for more docs for types and functions, I was more in the hope of getting explanations of how the different datastructures are supposed to be used together, what caveats there are.

I added a bit more, but I'm not clear on what parts are confusing?
Are you looking for an overview of the trie logic or something else?

2024-04-29 13:58 UTC, koxu1996 approved these changes
:rocket:

2024-04-29 14:12 UTC, marijanp commented on kairos-server/src/state/transactions/batch_state.rs
> +        if amount == 0 {
As discussed when we talked the last time, we are not going to do this

2024-04-29 14:37 UTC, marijanp commented on kairos-tx/src/asn.rs
> +                0b00001001, // L: 0b0 <- short form, 0b0001100 (9) <- length
Is this change still relevant?

2024-04-29 15:09 UTC, koxu1996 commented on kairos-tx/src/asn.rs
> +
Fixed in https://github.com/cspr-rad/kairos/pull/57/commits/6874e52e34e3b4d028d34e867683eb0e35ae5410.

2024-04-29 18:23 UTC, marijanp approved these changes
Thank you for adding the comments

2024-04-29 18:55 UTC, marijanp approved these changes

2024-04-29 18:55 UTC, merged